events {
    worker_connections 1024;
}

http {
    # Definición de los backends
    upstream usuarios_backend {
        server ms_usuarios:3000;
    }

    upstream manuscritos_backend {
        server ms_manuscritos:3000;
    }

    upstream analisis_backend {
        server ms_analisis:3000;
    }

    upstream matching_backend {
        server ms_matching:3000;
    }

    server {
        listen 80;

        # Ruta para USUARIOS
        location /api/usuarios/ {
            proxy_pass http://usuarios_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Ruta para MANUSCRITOS
        location /api/manuscritos/ {
            proxy_pass http://manuscritos_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Ruta para ANALISIS IA
        location /api/analisis/ {
            proxy_pass http://analisis_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Ruta para MATCHING
        location /api/matching/ {
            proxy_pass http://matching_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Página de bienvenida (Siempre al final)
        location / {
            return 200 'API Gateway de Sistema de Revision de Pares funcionando!';
            add_header Content-Type text/plain;
        }
    }
}